<?php

namespace AppBundle\Repository;

/**
 * AbstractDocumentClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractDocumentClientRepository extends \Doctrine\ORM\EntityRepository
{
}
