<?php

namespace AppBundle\Repository;

/**
 * BonDeCommandeFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonDeCommandeFournisseurRepository extends AbstractRepository
{


}
