<?php

namespace AppBundle\Repository;

/**
 * BonDeReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonDeReceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
