<?php

namespace AppBundle\Repository;

/**
 * CategorieTermeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieTermeRepository extends \Doctrine\ORM\EntityRepository
{
}
