<?php

namespace AppBundle\Repository;


/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    public function trouverSesClientsQB($commercialid){
    	return $this->createQueryBuilder('clients')
                	->where('clients.commercial = :commercial')
                	->setParameter(':commercial',  strval($commercialid))
                	->orderBy('clients.nom', 'ASC');	
    }
}
