<?php

namespace AppBundle\Repository;

/**
 * CommercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercialRepository extends \Doctrine\ORM\EntityRepository
{
}
