<?php

namespace AppBundle\Repository;

/**
 * ConditionsCommercialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsCommercialesRepository extends \Doctrine\ORM\EntityRepository
{
}
