<?php

namespace AppBundle\Repository;

/**
 * contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactRepository extends \Doctrine\ORM\EntityRepository
{
	    public function findThoseWhoWorkForSupplier(){
    	return $this->createQueryBuilder('contact')
                	->where('contact.fournisseur  IS NOT NULL')
                	->orderBy('contact.nom', 'ASC');	
    }

    public function findThoseWhoWorkFor($fournisseur){
        return $this->createQueryBuilder('contacts')
                    ->where('contacts.fournisseur = :fournisseur')
                    ->setParameter(':fournisseur',  strval($fournisseur))
                    ->orderBy('contacts.nom', 'ASC');
    }

    public function findDefaultWorkFor($fournisseur){

        return $this->createQueryBuilder('contact')
                    ->where('contact.fournisseur = :fournisseur')
                    ->andWhere('contact.defaut = :defaut')
                    ->setParameters(array('defaut' => 1, 'fournisseur' => $fournisseur))
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
