<?php

namespace AppBundle\Repository;

/**
 * EnteteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnteteRepository extends \Doctrine\ORM\EntityRepository
{
}
