<?php

namespace AppBundle\Repository;
use AppBundle\Search\PeriodCriteria;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends AbstractRepository
{
    public function findFactByPeriod(PeriodCriteria $criteria)
    {
        $qb = $this->createQueryBuilder('f');

        if (!empty($criteria->getStartDate())) {
            $qb->where('f.date >= :startDate')
                ->setParameter('startDate', $criteria->getStartDate());
        }

        if (!empty($criteria->getEndDate())) {
            $qb->andWhere('f.date <= :endDate')
                ->setParameter('endDate', $criteria->getEndDate());
        }
        return $qb->getQuery()->getResult();
    }
}
