<?php

namespace AppBundle\Repository;

/**
 * FinancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancementRepository extends \Doctrine\ORM\EntityRepository
{
}
