<?php

namespace AppBundle\Repository;

/**
 * garantieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class garantieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByAscNom(){
    	return $this->createQueryBuilder('record')
                	->orderBy('record.nom', 'ASC');	
    }
}
