<?php

namespace AppBundle\Repository;

/**
 * LieuStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuStockRepository extends \Doctrine\ORM\EntityRepository
{
}
