<?php

namespace AppBundle\Repository;

/**
 * lignePiedDePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignePiedDePageRepository extends \Doctrine\ORM\EntityRepository
{
}
