<?php

namespace AppBundle\Repository;

/**
 * LigneDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
