<?php

namespace AppBundle\Repository;

/**
 * LivraisonProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
