<?php

namespace AppBundle\Repository;

/**
 * modeleDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modeleDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
