<?php

namespace AppBundle\Repository;

/**
 * OpportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityRepository extends \Doctrine\ORM\EntityRepository
{
}
