<?php

namespace AppBundle\Repository;
use AppBundle\Entity\OpportunityStatus;
use AppBundle\Search\PeriodCriteria;

/**
 * OpportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByStatusCode($code)
    {
        return $this->createQueryBuilder('o')
            ->innerJoin('o.status', 's')
            ->where('s.code = :code')
            ->setParameter('code', $code)
            ->getQuery()
            ->getResult();
    }

    public function findByCriteria(PeriodCriteria $criteria)
    {
        $qb = $this->createQueryBuilder('o')
            ->innerJoin('o.status', 's')
            ->where('s.code in (:statusCode)')
            ->setParameter('statusCode', [OpportunityStatus::ECHU_CODE, OpportunityStatus::NCOURS_CODE]);

        if (!empty($criteria->getStartDate())) {
            $qb->andWhere('o.createdAt >= :startDate')
                ->setParameter('startDate', $criteria->getStartDate());
        }

        if (!empty($criteria->getEndDate())) {
            $qb->andWhere('o.createdAt <= :endDate')
                ->setParameter('endDate', $criteria->getEndDate());
        }

        return $qb->getQuery()->getResult();
    }
}
