<?php

namespace AppBundle\Repository;

/**
 * OpportunityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
