<?php

namespace AppBundle\Repository;

/**
 * OProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OProductRepository extends \Doctrine\ORM\EntityRepository
{
}
