<?php

namespace AppBundle\Repository;

/**
 * piedDePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class piedDePageRepository extends \Doctrine\ORM\EntityRepository
{
}
