<?php

namespace AppBundle\Repository;

/**
 * ProduitFusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFusionRepository extends \Doctrine\ORM\EntityRepository
{
}
