<?php

namespace AppBundle\Repository;

/**
 * ProduitBCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitBCRepository extends \Doctrine\ORM\EntityRepository
{

}
