<?php

namespace AppBundle\Repository;

/**
 * ProduitLigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitLigneRepository extends \Doctrine\ORM\EntityRepository
{
}
