<?php

namespace AppBundle\Repository;

/**
 * ProduitDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitDevisRepository extends \Doctrine\ORM\EntityRepository
{

    public function findArray($id){

        return $this->createQueryBuilder('produit')
                    ->where('produit.id = :id')
                    ->setParameters(array('id' => $id))
                    ->getQuery()
                    ->getArrayResult();
    }

    public function Rapport($user){

        return $this->createQueryBuilder('produit commercial')
                    ->innerJoin('produit.devis', 'devis')
                    ->innerJoin('devis.commercial', 'commercial')
                    ->where('commercial.id = :id')
                    ->setParameters(array('id' => $user->getId()))
                    ->getQuery();
                    // ->getArrayResult();
    }

}
