<?php

namespace AppBundle\Repository;

/**
 * ReceptionProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
