<?php

namespace AppBundle\Repository;

/**
 * RfpModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RfpModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
