<?php

namespace AppBundle\Repository;

/**
 * RfpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RfpRepository extends \Doctrine\ORM\EntityRepository
{
}
