<?php

namespace AppBundle\Repository;

/**
 * StatutTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
