<?php

namespace AppBundle\Repository;

/**
 * statutProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
