<?php

namespace AppBundle\Repository;

/**
 * TechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologyRepository extends \Doctrine\ORM\EntityRepository
{
}
