<?php

namespace AppBundle\Repository;

/**
 * TermesDevis_RRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermesDevis_RRepository extends \Doctrine\ORM\EntityRepository
{
}
