<?php

namespace AppBundle\Repository;

/**
 * TicketStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
