<?php

namespace AppBundle\Repository;

/**
 * TicketHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
