<?php

namespace AppBundle\Repository;

/**
 * TravailLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
	 public function findAllByDescCharge(){
	 	return 	$this->createQueryBuilder('TravailLivraison')->orderBy('TravailLivraison.charge', 'DESC');
	 }
}
