<?php

namespace AppBundle\Repository;

/**
 * TravailCommercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailCommercialRepository extends \Doctrine\ORM\EntityRepository
{

	 public function findAllByDescCharge(){
	 	return 	$this->createQueryBuilder('TravailLivraison')->orderBy('TravailLivraison.charge', 'DESC');
	 }
	
}
