imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    container.autowiring.strict_mode: true

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
            - bootstrap_3_layout.html.twig
    globals:
        nicedit_icon: '/js/nicEditorIcons.gif'
        company_name: '%company_name%'
        company_legal_name: 'SOLDAT S.A.R.L'
        director: 'Salim El Jaï'
        function: 'Directeur Général-Gérant'
        mobile_phone: '+212 5 29 04 17 45'
        fax: '+212 5 29 04 09 01'
        email: 'seljai@solutiondata.fr'
        cnss: '5799749'
        rc: '393609'
        patente: '36191840'
        bank_account_number: '011780000016210001127789'
        capital: '500 000 Dirhams'
        address1: '1100 Boulevard Al Qods Régus, Shore1, 20190 Casablanca Maroc'
       # address2: '22 Rue du parc, Régus le théâtre 20100 Casablanca, Maroc.'
        address2: '14, Boulevard Yacoub El Mansour 2° étage bureau n° 3'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                year: DoctrineExtensions\Query\Mysql\Year
                month: DoctrineExtensions\Query\Mysql\Month
                day: DoctrineExtensions\Query\Mysql\DAY
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: '%locale%'
    translation_fallback: true
    orm:
        default:
            tree: true
            translatable: true
            timestampable: true
            softdeleteable: true
            sluggable: true
            blameable: true

